# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170416_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.JobPosting'),
        ),
    ]
