# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_candidate_job_posting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventjob',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventjob',
            name='job_posting',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='job_posting',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='selected_job_posting',
            field=models.ForeignKey(blank=True, help_text='Select Job Posting you are interested in.', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.JobPosting'),
        ),
        migrations.AddField(
            model_name='event',
            name='job_postings',
            field=models.ManyToManyField(blank=True, help_text='Select all Job Postings being recruited for this Event.', to='events.JobPosting'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='EventJob',
        ),
    ]
