# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170416_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='selected_job_posting',
            field=models.ForeignKey(default=1, help_text='Select Job Posting you are interested in.', on_delete=django.db.models.deletion.CASCADE, to='events.JobPosting'),
            preserve_default=False,
        ),
    ]
