# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_candidate_attended_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['event'],
            },
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='attended_event',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='selected_job_posting',
        ),
        migrations.AddField(
            model_name='attendance',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Candidate'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='selected_job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.JobPosting'),
        ),
    ]
