# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-13 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170423_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='selected_jobs',
            field=models.ManyToManyField(through='events.Attendance', to='events.JobPosting'),
        ),
    ]
