# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-02 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0006_auto_20190402_1918'),
        ('events', '0010_candidate_selected_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_email',
            field=models.BooleanField(default=False, verbose_name='Auto send Email on Registration'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_template',
            field=models.ForeignKey(blank=True, help_text='Select the email template for auto-sending emails at this event.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sendemail.EmailTemplate'),
        ),
    ]
