# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-05 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190402_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_email_from',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='From Email Address for Auto Send Emails'),
        ),
    ]
