# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_auto_email_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='auto_email',
            field=models.BooleanField(default=False, verbose_name='Auto send email on registration'),
        ),
        migrations.AlterField(
            model_name='event',
            name='auto_email_from',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Auto send from email'),
        ),
    ]
