# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
