# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-27 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_candidate_selected_jobs'),
        ('sendemail', '0002_emailtemplate_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=200, verbose_name='To')),
                ('from_address', models.CharField(max_length=200, verbose_name='From')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('time_sent', models.DateTimeField()),
                ('body', tinymce.models.HTMLField()),
                ('response', models.TextField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Candidate')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
