# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-27 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0003_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='body',
            field=tinymce.models.HTMLField(editable=False),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='from_address',
            field=models.CharField(editable=False, max_length=200, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='response',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(editable=False, max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='time_sent',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='to_address',
            field=models.CharField(editable=False, max_length=200, verbose_name='To'),
        ),
    ]
