# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0004_auto_20190327_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='bcc_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='To'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='cc_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='from_address',
            field=models.CharField(max_length=200, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='response',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='time_sent',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='to_address',
            field=models.CharField(max_length=200, verbose_name='To'),
        ),
    ]
