# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-02 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0005_auto_20190329_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='bcc_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='BCC'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='cc_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CC'),
        ),
    ]
